### ISSUE TITLE
Reproduce visualization of the current ECAL

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#24]
Talk about event display with PHEONIX:
https://indico.fnal.gov/event/62016/contributions/280439/subcontributions/9317/attachments/174135/236005/EventDisplay_LDMX_Jan11.pdf
gdml_to_gltf: https://github.com/LDMX-Software/ldmx-sw/tree/888-eventdisplay-re-design/EventDisplay/gdml_to_gltf
ECAL GDML: https://github.com/LDMX-Software/ldmx-sw/blob/trunk/Detectors/data/ldmx-det-v14-8gev/ecal.gdml

**Comment by DuncanWilmot** [comment]
Based on the discussion yesterday, I think we can close this. 

Steps:
1) Hack away at flattened for loops in [fulldetector.gdml](https://github.com/LDMX-Software/ldmx-sw/blob/888-eventdisplay-re-design/EventDisplay/gdml_to_gltf/fulldetector.gdml) to isolate parts of the detector (should be able to do this in Phoenix front-end?)
2) Also used some custom gdml's and the [gdml_to_gltf](https://github.com/LDMX-Software/ldmx-sw/tree/888-eventdisplay-re-design/EventDisplay/gdml_to_gltf) conversion works fine
3) Load geometry with [Phoenix](https://github.com/HSF/phoenix) (easiest way is simply to use the [online playground](https://hepsoftwarefoundation.org/phoenix/#/playground))

Findings:
1) ECal flower in XY plane shown here (center module from front of bilayer in foreground, entire flower from back of bilayer shown in background, shifted to the left i.e., positive x):
![image](https://github.com/IncandelaLab/LDMX-scripts/assets/71404398/c40f17af-8d10-4574-8dbe-a68a761d100a)
2) Cells (hexagons) on sensor rotated by pi/6 relative to sensor (larger hexagon), meaning the shift at the cell-level looks like this:
![ecal_cell_offset_flip](https://github.com/IncandelaLab/LDMX-scripts/assets/71404398/344467b2-93b6-4f43-8071-89c615ed5d9f)
3) [v14 gdml](https://github.com/LDMX-Software/ldmx-sw/blob/trunk/Detectors/data/ldmx-det-v14-8gev/constants.gdml#L404-L420) claims offset it flat-to-flat cell diameter, but specifies ~4.8mm, which is most consistent with a measured value of cell side-length for a high density sensor (meaning center of front cell is shifted to triple-point of back cells as desired)

**Comment by tvami** [comment]
Indeed! Good job @DuncanWilmot !
