### ISSUE TITLE
Trigger studies for DM signals

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#29]
## Tasks

- [ ] Look at pT vs eff for signal
- [ ] Look at MET vs eff for signal

## Existing material to start off

 * One handy way to do this is to fill a 2D histogram in ROOT with one axis having 2 bins (-0.5-0.5 and 0.5-1.5) filling 0 when the trigger is not fired and filling 1 when it is; then the other axis is the parameter of interest. Then take a `TProfile` in the boolean axis and that's it

**Comment by DuncanWilmot** [comment]
FYI it turns out trigger efficiencies are more like this:
```
Trigger efficiencies:{
    "0.001": 0.7723346153846153,
    "0.01": 0.8991299107142857,
    "0.1": 0.9228279816513761,
    "1.0": 0.9370799065420561,
}
```

I can make pT and ME plots before Wednesday if this is time-sensitive (also LDMX can measure true total missing energy, but maybe MET calculations still possible/useful?)

**Comment by tvami** [comment]
Thanks @DuncanWilmot , this makes more sense indeed! It's not time sensitive and also could be a small project from one of the incoming undergrads.
